---
- name: nginx_Playbook
  hosts: localhost
  become_method: su
  become_exe: sudo su -
  tasks:
  - name: nginx
    become: yes
    apt:
      name: nginx
      state: present
    tags: install_nginx
  - name: nginx
    become: yes
    apt:
      name: nginx
      state: absent
    tags: uninstall_nginx
  - name: ping localhost
    ping:
  - name: Print a message
    debug:
      msg: "Hello, World!"
