---
- name: User Playbook
  hosts: localhost
  become: yes
  become_method: su
  become_exe: sudo su -
  vars_files:
  - package_list.yml

  tasks:
  # install packages
  - name: Install packages
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    loop: "{{ package_to_install }}"
    tags: install_package

  # uninstall packages
  - name: Uninstall packages
    become: yes
    apt:
      name: "{{ item }}"
      state: absent
    loop: "{{ package_to_uninstall }}"
    tags: uninstall_package

  - name: Ping localhost
    ping:


  - name: Print a message
    debug:
      msg: "Hello, World!"
