---
- name: user_Playbook
  hosts: localhost
  become_method: su
  become_exe: sudo su -
  tasks:
  - name: "{{ package_name }}"
    become: yes
    apt:
      name: "{{ package_name }}"
      state: present
    tags: install_package
  - name: "{{ package_name }}"
    become: yes
    apt:
      name: "{{ package_name }}"
      state: absent
    tags: uninstall_package
  - name: ping localhost
    ping:
  - name: Print a message
    debug:
      msg: "Hello, World!"
